openapi: 3.0.3
info:
  title: Argent Bank Transactions API
  description: Basic API model for transactions (Phase 2)
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1

paths:
  /user/transactions:
    get:
      tags:
        - Transactions
      summary: Get all transactions for current month
      description: Returns all user transactions for the current month, grouped by account
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of transactions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "401":
          description: Unauthorized
        "404":
          description: Transactions not found
        "500":
          description: Internal server error

  /user/transaction/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Get transaction details
      description: Returns the details of a specific transaction
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID of the transaction
      responses:
        "200":
          description: Transaction details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal server error

    put:
      tags:
        - Transactions
      summary: Update a transaction
      description: Update the category or note of a transaction
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID of the transaction to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: Food
                note:
                  type: string
                  example: "lorem ipsum"
      responses:
        "200":
          description: Transaction updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          example: "txn_0001"
        date:
          type: string
          format: date
          example: "2020-02-27"
        amount:
          type: number
          example: 8.00
        description:
          type: string
          example: "Golden Sun Bakery"
        type:
          type: string
          example: "Electronic"
        category:
          type: string
          example: "Food"
        note:
          type: string
          example: "lorem ipsum"
        balance:
          type: number
          example: 298.00
